version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    ports: 
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0
    ports:
      - 5601:5601
