version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    ports: 
      - 9200:9200
      - 9300:9300
    volumes:
      - ./config/analysis:/usr/share/elasticsearch/config/analysis
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    ports:
      - 5601:5601
